Revert "fix: top running pods"
This reverts commit 3520057e7ce2754254f2c34897be76a4cde58ea4.

V1PodStatus.PhaseEnum does not exist, causing topNodes to crash with the
following error:

TypeError: Cannot read properties of undefined (reading 'Running')
    at /home/user/code/misc/k8s-js-bug/node_modules/@kubernetes/client-node/dist/top.js:61:92
    at Array.filter (<anonymous>)
    at Object.topNodes (/home/user/code/misc/k8s-js-bug/node_modules/@kubernetes/client-node/dist/top.js:59:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/user/code/misc/k8s-js-bug/main.js:10:21)